export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const CHANGE_THEME = 'CHANGE_THEME'

export const DISABLE_BUTTONS = 'DISABLE BUTTONS'
export const ENABLE_BUTTONS = 'ENABLE BUTTONS'